### PR TITLE
Operations comments

### PR DESCRIPTION
**Pull request by jesusjuansalgado**

### CODE REVIEW

**Review by lmichel — DISMISSED** [review]

**Review by mbtaylor — APPROVED** [review]
This looks good, thank you for the changes.  There are still some adjustments I would suggest to the data type requirements which I will address in a separate PR.

**Comment by mbtaylor** [comment]
Github says I "dismissed @lmichel 's stale review".  I don't know how I did that or if it matters - sorry Laurent!

**Comment by jesusjuansalgado** [comment]
Thanks @mbtaylor. Whenever you have the comments on the data types. I can include them
I am not sure if the white-space added by @lmichel is included but I take note (I need to do other changes)
I merge anyway and I take note of it

**Comment by mbtaylor** [comment]
The whitespace was mine - it does seem to be included.

**Pull request merged**
