### PR TITLE
Remove unnecessary obs_release_date field

### PR DESCRIPTION
**Pull request by jesusjuansalgado**

### CODE REVIEW

**Comment by mbtaylor** [comment]
If this field is being removed, you should also remove the note after the table
```
{\it (date)\/} means Timestamp string values as described in DALI
```
since there are no longer any `(date)`-labelled fields in the obsplan table.

**Comment by mbtaylor** [comment]
Also, the comments in the table parts of the LaTeX source now go straight from `%row no:22` to `%row no:24`, which is a bit confusing/surprising.

**Comment by jesusjuansalgado** [comment]
Thanks Mark! I have corrected the text for the two comments (remove date explanation and comments order number)

**Review by mbtaylor — COMMENTED** [review]
Looks fine to me now.

**Review by mbtaylor — APPROVED** [review]

**Pull request merged**
